# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-07 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('creation_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_deadline', models.TimeField(auto_now_add=True)),
                ('task_descrip', models.TextField()),
                ('task_status', models.CharField(max_length=25)),
                ('task_creation_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('usr_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=500, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsrActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.TimeField(auto_now_add=True)),
                ('usr_email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='ZenVector.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UsrProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='ZenVector.Projects')),
                ('usr_email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='ZenVector.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UsrTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='ZenVector.Tasks')),
                ('usr_email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='ZenVector.Users')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_given_by',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='ZenVector.Users'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='ZenVector.Projects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='usr_email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='ZenVector.Users'),
        ),
    ]
