# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZenVector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='ZenVector.Projects')),
            ],
        ),
    ]
