# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZenVector', '0002_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_status',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_state',
            field=models.ForeignKey(db_column='state_name', default=0, on_delete=django.db.models.deletion.CASCADE, to='ZenVector.state'),
            preserve_default=False,
        ),
    ]
