# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenVector', '0003_auto_20191109_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_deadline',
            field=models.DateField(auto_now_add=True),
        ),
    ]
