# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-19 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenVector', '0005_auto_20191118_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_color',
            field=models.CharField(default='#59A61E', max_length=255),
        ),
    ]
