# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenVector', '0006_tasks_task_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_color',
        ),
        migrations.AddField(
            model_name='state',
            name='state_color',
            field=models.CharField(default='#59A61E', max_length=255),
        ),
    ]
