# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenVector', '0007_auto_20191119_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_type',
            field=models.CharField(default='F', max_length=5),
            preserve_default=False,
        ),
    ]
