# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-08 17:15
from __future__ import unicode_literals

import ZenVector.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZenVector', '0008_users_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=ZenVector.models.random_pass, max_length=15)),
                ('usr_email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
