# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-12 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenVector', '0009_passwordcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordcodes',
            name='isUsed',
            field=models.BooleanField(default=False),
        ),
    ]
