# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenVector', '0010_passwordcodes_isused'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_position',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
