# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ZenVector', '0011_tasks_task_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
