# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-19 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZenVector', '0013_projects_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usractivity',
            name='usr_email',
        ),
        migrations.DeleteModel(
            name='UsrActivity',
        ),
    ]
