language: python

python:
  - "2.7"

script:
  - cd Django
  - python manage.py test

env:
  - DJANGO_VERSION=1.11.25

install:
  - pip install -q Django==$DJANGO_VERSION

notifications:
  email:
    recipients:
      - fahedshaabani@std.sehir.edu.tr
    on_success: never # default: change
    on_failure: always # default: always