language: python

python:
  - "2.7"

script:
  - cd Django
  - python manage.py test
notifications:
  email:
    recipients:
      - fahedshaabani@std.sehir.edu.tr
    on_success: never # default: change
    on_failure: always # default: always